### ISSUE TITLE
Seal of Command batching with Seal of Blood

### ISSUE THREAD

**Issue by LettuceSealTwistPlease** [Tauri-WoW-Community-Devs/TauriApiWrapper#1]
So i've noticed this server in particular has no window for batching for ret paladins. This was possible back in 2007 on the original TBC client and also just recently this past year on Classic TBC. Is there any particular reason why this was changed for this server? I noticed alliance was given Seal of Blood, but just curious as to why theres no batching window for Seal of Command into Seal of Blood. Thanks for your time and i hope to hear back from you!

**Comment by snwflake** [comment]
This is the repository for a dotnet wrapper around tauris web api.....
It has nothing to do with TBC, MoP, Tauris realms or stormforge?!?

Man, people.....

**Comment by LettuceSealTwistPlease** [comment]
Idky the GMs are linking to this to post the concern here my bad.

**Comment by snwflake** [comment]
that's because stormforge GMs are braindead monkeys....
