### ISSUE TITLE
Issue with ItemResponse Class Definition

### ISSUE THREAD

**Issue by muhnow** [Tauri-WoW-Community-Devs/TauriApiWrapper#52]
**Describe the bug**
I uncovered an exception when attempting to retrieve an item by ID using the tooltip client.

The `SpellTrigger` property on the `ItemReponse` class is too small of a data type for potential response values from the Tauri Item Api.

**To Reproduce**
1. Make a request using the `TooltipClient` using the `GetItemByID` method with 77534 as the provided item ID.

**Expected behavior**
The proper response is returned without any exceptions encountered. Ideally, this array of numbers should just be type `long` since potential values fall outside of the range for int32. 

**Screenshots**
![image](https://user-images.githubusercontent.com/45505818/152704377-6cb8b87c-e0b0-4bb4-9fe8-02a76a3c5add.png)

**Comment by query-wow** [comment]
Fixed in https://github.com/Tauri-WoW-Community-Devs/TauriApiWrapper/commit/cd9704f9c8eb649506a1249f9c712ea76e10a1b2
