### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by query-wow** [Tauri-WoW-Community-Devs/TauriApiWrapper#7]
There's the need of adding documentation to all the objects of the API

**Comment by nikhil-mukunda** [comment]
Hi!

I'm a technical writer and I'd like to contribute. Would this be a RESTful API?

Thanks!

**Comment by query-wow** [comment]
Hi  @nikhil-mukunda, this is just a wrapper for an actual API that already exists, currently all the objects have been mapped, so as their own endpoints. The goal of the documentation is to describe what object does and what it is. Same apply for the methods
